# openapi2-functions.yaml
swagger: '2.0'
info:
  title: api-zzi
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
securityDefinitions:
   # This section configures basic authentication with an API key.
   api_key:
     type: "apiKey"
     name: "key"
     in: "query"
x-google-backend:
  address: https://polls-service-jhoan-te7xy2moeq-uc.a.run.app
paths:
  /:
    get:
      summary: root
      operationId: root
      responses:
        '200':
          description: A successful response
          schema:
            type: string

  /api/questions:
    get:
      summary: Greet a user
      operationId: questions_list
      security: 
      - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string

  /test:
    get:
      summary: test
      operationId: test
      security: 
      - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string

  /api/choice:
    get:
      summary: choice
      operationId: choice_list
      security: 
      - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string